from django.utils.translation import gettext_lazy

address_countrycodes = (  # FIXME: Translate from spanish to english
    ('AF', gettext_lazy('Afganistán')),
    ('AL', gettext_lazy('Albania')),
    ('DE', gettext_lazy('Alemania')),
    ('AD', gettext_lazy('Andorra')),
    ('AO', gettext_lazy('Angola')),
    ('AI', gettext_lazy('Anguila')),
    ('AG', gettext_lazy('Antigua y Barbuda')),
    ('AN', gettext_lazy('Antillas Holandesas')),
    ('AQ', gettext_lazy('Antártida')),
    ('SA', gettext_lazy('Arabia Saudita')),
    ('DZ', gettext_lazy('Argelia')),
    ('AR', gettext_lazy('Argentina')),
    ('AM', gettext_lazy('Armenia')),
    ('AW', gettext_lazy('Aruba')),
    ('AU', gettext_lazy('Australia')),
    ('AT', gettext_lazy('Austria')),
    ('AZ', gettext_lazy('Azerbaiyán')),
    ('BS', gettext_lazy('Bahamas')),
    ('BH', gettext_lazy('Bahráin')),
    ('BD', gettext_lazy('Bangladesh')),
    ('BB', gettext_lazy('Barbados')),
    ('BZ', gettext_lazy('Belice')),
    ('BJ', gettext_lazy('Benín')),
    ('BM', gettext_lazy('Bermudas')),
    ('BY', gettext_lazy('Bielorrusia')),
    ('BO', gettext_lazy('Bolivia')),
    ('BQ', gettext_lazy('Bonaire, San Eustaquio y Saba')),
    ('BA', gettext_lazy('Bosnia y Hercegovina')),
    ('BW', gettext_lazy('Botsuana')),
    ('BR', gettext_lazy('Brasil')),
    ('BN', gettext_lazy('Brunéi')),
    ('BG', gettext_lazy('Bulgaria')),
    ('BF', gettext_lazy('Burkina Faso')),
    ('BI', gettext_lazy('Burundi')),
    ('BT', gettext_lazy('Bután')),
    ('BE', gettext_lazy('Bélgica')),
    ('CV', gettext_lazy('Cabo Verde')),
    ('KH', gettext_lazy('Camboya')),
    ('CM', gettext_lazy('Camerún')),
    ('CA', gettext_lazy('Canadá')),
    ('TD', gettext_lazy('Chad')),
    ('CZ', gettext_lazy('Chequia')),
    ('CL', gettext_lazy('Chile')),
    ('CN', gettext_lazy('China')),
    ('CY', gettext_lazy('Chipre')),
    ('VA', gettext_lazy('Ciudad del Vaticano')),
    ('CO', gettext_lazy('Colombia')),
    ('KM', gettext_lazy('Comores')),
    ('CG', gettext_lazy('Congo')),
    ('KP', gettext_lazy('Corea del Norte')),
    ('KR', gettext_lazy('Corea del Sur')),
    ('CR', gettext_lazy('Costa Rica')),
    ('CI', gettext_lazy('Costa de Marfil')),
    ('HR', gettext_lazy('Croacia')),
    ('CU', gettext_lazy('Cuba')),
    ('CW', gettext_lazy('Curaçao')),
    ('DK', gettext_lazy('Dinamarca')),
    ('DM', gettext_lazy('Dominica')),
    ('EC', gettext_lazy('Ecuador')),
    ('EG', gettext_lazy('Egipto')),
    ('SV', gettext_lazy('El Salvador')),
    ('AE', gettext_lazy('Emiratos Árabes Unidos')),
    ('ER', gettext_lazy('Eritrea')),
    ('SK', gettext_lazy('Eslovaquia')),
    ('SI', gettext_lazy('Eslovenia')),
    ('ES', gettext_lazy('España')),
    ('US', gettext_lazy('Estados Unidos')),
    ('EE', gettext_lazy('Estonia')),
    ('ET', gettext_lazy('Etiopía')),
    ('PH', gettext_lazy('Filipinas')),
    ('FI', gettext_lazy('Finlandia')),
    ('FJ', gettext_lazy('Fiyi')),
    ('FR', gettext_lazy('Francia')),
    ('GA', gettext_lazy('Gabón')),
    ('GM', gettext_lazy('Gambia')),
    ('GE', gettext_lazy('Georgia')),
    ('GH', gettext_lazy('Ghana')),
    ('GI', gettext_lazy('Gibraltar')),
    ('GD', gettext_lazy('Granada')),
    ('GR', gettext_lazy('Grecia')),
    ('GL', gettext_lazy('Groenlandia')),
    ('GP', gettext_lazy('Guadalupe')),
    ('GU', gettext_lazy('Guam')),
    ('GT', gettext_lazy('Guatemala')),
    ('GF', gettext_lazy('Guayana Francesa')),
    ('GG', gettext_lazy('Guernsey')),
    ('GN', gettext_lazy('Guinea')),
    ('GQ', gettext_lazy('Guinea Ecuatorial')),
    ('GW', gettext_lazy('Guinea-Bissau')),
    ('GY', gettext_lazy('Guyana')),
    ('HT', gettext_lazy('Haití')),
    ('NL', gettext_lazy('Holanda')),
    ('HN', gettext_lazy('Honduras')),
    ('HK', gettext_lazy('Hong Kong')),
    ('HU', gettext_lazy('Hungría')),
    ('IN', gettext_lazy('India')),
    ('ID', gettext_lazy('Indonesia')),
    ('IQ', gettext_lazy('Iraq')),
    ('IE', gettext_lazy('Irlanda')),
    ('IR', gettext_lazy('Irán')),
    ('BV', gettext_lazy('Isla Bouvet')),
    ('CX', gettext_lazy('Isla Christmas')),
    ('NF', gettext_lazy('Isla Norfolk')),
    ('IM', gettext_lazy('Isla de Man')),
    ('IS', gettext_lazy('Islandia')),
    ('AX', gettext_lazy('Islas Aland')),
    ('KY', gettext_lazy('Islas Caimán')),
    ('CC', gettext_lazy('Islas Cocos')),
    ('CK', gettext_lazy('Islas Cook')),
    ('FO', gettext_lazy('Islas Feroe')),
    ('GS', gettext_lazy('Islas Georgia del Sur y Sandwich del Sur')),
    ('HM', gettext_lazy('Islas Heard y McDonald')),
    ('FK', gettext_lazy('Islas Malvinas')),
    ('MP', gettext_lazy('Islas Marianas del Norte')),
    ('MH', gettext_lazy('Islas Marshall')),
    ('PN', gettext_lazy('Islas Pitcairn')),
    ('SB', gettext_lazy('Islas Salomón')),
    ('TC', gettext_lazy('Islas Turcas y Caicos')),
    ('VI', gettext_lazy('Islas Vírgenes Americanas')),
    ('VG', gettext_lazy('Islas Vírgenes Británicas')),
    ('UM', gettext_lazy('Islas menores alejadas de los Estados Unidos')),
    ('IL', gettext_lazy('Israel')),
    ('IT', gettext_lazy('Italia')),
    ('JM', gettext_lazy('Jamaica')),
    ('JP', gettext_lazy('Japón')),
    ('JE', gettext_lazy('Jersey')),
    ('JO', gettext_lazy('Jordania')),
    ('KZ', gettext_lazy('Kazajstán')),
    ('KE', gettext_lazy('Kenia')),
    ('KG', gettext_lazy('Kirguizistán')),
    ('KI', gettext_lazy('Kiribati')),
    ('KW', gettext_lazy('Kuwait')),
    ('LA', gettext_lazy('Laos')),
    ('LS', gettext_lazy('Lesoto')),
    ('LV', gettext_lazy('Letonia')),
    ('LR', gettext_lazy('Liberia')),
    ('LY', gettext_lazy('Libia')),
    ('LI', gettext_lazy('Liechtenstein')),
    ('LT', gettext_lazy('Lituania')),
    ('LU', gettext_lazy('Luxemburgo')),
    ('LB', gettext_lazy('Líbano')),
    ('MO', gettext_lazy('Macao')),
    ('MK', gettext_lazy('Macedonia')),
    ('MG', gettext_lazy('Madagascar')),
    ('MY', gettext_lazy('Malasia')),
    ('MW', gettext_lazy('Malaui')),
    ('MV', gettext_lazy('Maldivas')),
    ('MT', gettext_lazy('Malta')),
    ('ML', gettext_lazy('Malí')),
    ('MA', gettext_lazy('Marruecos')),
    ('MQ', gettext_lazy('Martinica')),
    ('MU', gettext_lazy('Mauricio')),
    ('MR', gettext_lazy('Mauritania')),
    ('YT', gettext_lazy('Mayotte')),
    ('FM', gettext_lazy('Micronesia')),
    ('MD', gettext_lazy('Moldavia')),
    ('MN', gettext_lazy('Mongolia')),
    ('ME', gettext_lazy('Montenegro')),
    ('MS', gettext_lazy('Montserrat')),
    ('MZ', gettext_lazy('Mozambique')),
    ('MM', gettext_lazy('Myanmar')),
    ('MX', gettext_lazy('México')),
    ('MC', gettext_lazy('Mónaco')),
    ('NA', gettext_lazy('Namibia')),
    ('NR', gettext_lazy('Nauru')),
    ('NP', gettext_lazy('Nepal')),
    ('NI', gettext_lazy('Nicaragua')),
    ('NG', gettext_lazy('Nigeria')),
    ('NU', gettext_lazy('Niue')),
    ('NO', gettext_lazy('Noruega')),
    ('NC', gettext_lazy('Nueva Caledonia')),
    ('NZ', gettext_lazy('Nueva Zelanda')),
    ('NE', gettext_lazy('Níger')),
    ('OM', gettext_lazy('Omán')),
    ('PW', gettext_lazy('Palaos')),
    ('PS', gettext_lazy('Palestina')),
    ('PA', gettext_lazy('Panamá')),
    ('PG', gettext_lazy('Papúa New Guinea')),
    ('PK', gettext_lazy('Paquistán')),
    ('PY', gettext_lazy('Paraguay')),
    ('PE', gettext_lazy('Perú')),
    ('PF', gettext_lazy('Polinesia Francesa')),
    ('PL', gettext_lazy('Polonia')),
    ('PT', gettext_lazy('Portugal')),
    ('PR', gettext_lazy('Puerto Rico')),
    ('QA', gettext_lazy('Qatar')),
    ('GB', gettext_lazy('Reino Unido')),
    ('CF', gettext_lazy('República Centroafricana')),
    ('CD', gettext_lazy('República Democrática del Congo')),
    ('DO', gettext_lazy('República Dominicana')),
    ('RE', gettext_lazy('Reunión')),
    ('RW', gettext_lazy('Ruanda')),
    ('RO', gettext_lazy('Rumania')),
    ('RU', gettext_lazy('Rusia')),
    ('EH', gettext_lazy('Sahara Occidental')),
    ('WS', gettext_lazy('Samoa')),
    ('AS', gettext_lazy('Samoa Americana')),
    ('BL', gettext_lazy('San Bartolomé')),
    ('KN', gettext_lazy('San Cristóbal y Nieves')),
    ('SM', gettext_lazy('San Marino')),
    ('MF', gettext_lazy('San Martín')),
    ('SX', gettext_lazy('San Martín (región holandesa)')),
    ('PM', gettext_lazy('San Pedro y Miquelón')),
    ('VC', gettext_lazy('San Vicente y las Granadinas')),
    ('SH', gettext_lazy('Santa Helena')),
    ('LC', gettext_lazy('Santa Lucia')),
    ('ST', gettext_lazy('Santo Tomé y Príncipe')),
    ('SN', gettext_lazy('Senegal')),
    ('RS', gettext_lazy('Serbia')),
    ('SC', gettext_lazy('Seychelles')),
    ('SL', gettext_lazy('Sierra Leona')),
    ('SG', gettext_lazy('Singapur')),
    ('SY', gettext_lazy('Siria')),
    ('SO', gettext_lazy('Somalia')),
    ('LK', gettext_lazy('Sri Lanka')),
    ('SZ', gettext_lazy('Suazilandia')),
    ('ZA', gettext_lazy('Sudáfrica')),
    ('SD', gettext_lazy('Sudán')),
    ('SS', gettext_lazy('Sudán del Sur')),
    ('SE', gettext_lazy('Suecia')),
    ('CH', gettext_lazy('Suiza')),
    ('SR', gettext_lazy('Surinam')),
    ('SJ', gettext_lazy('Svalbard y Jan Mayen')),
    ('TH', gettext_lazy('Tailandia')),
    ('TW', gettext_lazy('Taiwán')),
    ('TZ', gettext_lazy('Tanzania')),
    ('TJ', gettext_lazy('Tayikistán')),
    ('IO', gettext_lazy('Territorio Británico del Océano Índico')),
    ('TF', gettext_lazy('Territorios Franceses del Sur')),
    ('TL', gettext_lazy('Timor Oriental')),
    ('TG', gettext_lazy('Togo')),
    ('TK', gettext_lazy('Tokelau')),
    ('TO', gettext_lazy('Tonga')),
    ('TT', gettext_lazy('Trinidad y Tobago')),
    ('TM', gettext_lazy('Turkmenistán')),
    ('TR', gettext_lazy('Turquía')),
    ('TV', gettext_lazy('Tuvalu')),
    ('TN', gettext_lazy('Túnez')),
    ('UA', gettext_lazy('Ucrania')),
    ('UG', gettext_lazy('Uganda')),
    ('UY', gettext_lazy('Uruguay')),
    ('UZ', gettext_lazy('Uzbekistán')),
    ('VU', gettext_lazy('Vanuatu')),
    ('VE', gettext_lazy('Venezuela')),
    ('VN', gettext_lazy('Vietnam')),
    ('WF', gettext_lazy('Wallis y Futuna')),
    ('YE', gettext_lazy('Yemen')),
    ('DJ', gettext_lazy('Yibuti')),
    ('ZM', gettext_lazy('Zambia')),
    ('ZW', gettext_lazy('Zimbabue')),
)

card_brands_unknown = 'unknown'
card_brands_visa = 'visa'
card_brands_mastercard = 'mastercard'
card_brands_carnet = 'carnet'
card_brands_american = 'american_express'
card_brands_american2 = 'american express'
card_brands = (
    (card_brands_unknown, gettext_lazy('Unknown')),
    (card_brands_visa, gettext_lazy('Visa')),
    (card_brands_mastercard, gettext_lazy('Mastercard')),
    (card_brands_carnet, gettext_lazy('Carnet')),
    (card_brands_american, gettext_lazy('American Express')),
    (card_brands_american2, gettext_lazy('American Express')),
)

plan_currency_mxn = 'MXN'
plan_currency_usd = 'USD'
plan_currency = (
    (plan_currency_mxn, gettext_lazy('MXN')),
    (plan_currency_usd, gettext_lazy('USD')),
)
plan_status_active = 'active'
plan_status_deleted = 'deleted'
plan_status = (
    (plan_status_active, gettext_lazy('Active')),
    (plan_status_deleted, gettext_lazy('Deleted')),
)
plan_statusafter_unpaid = 'unpaid'
plan_statusafter_cancelled = 'cancelled'
plan_statusafter = (
    (plan_statusafter_unpaid, gettext_lazy('Unpaid')),
    (plan_statusafter_cancelled, gettext_lazy('Cancelled')),
)
plan_repeatunit_week = 'week'
plan_repeatunit_month = 'month'
plan_repeatunit_year = 'year'
plan_repeatunit = (
    (plan_repeatunit_week, gettext_lazy('Week')),
    (plan_repeatunit_month, gettext_lazy('Month')),
    (plan_repeatunit_year, gettext_lazy('Year')),
)

subscription_status_trial = 'trial'
subscription_status_active = 'active'
subscription_status_pastdue = 'past_due'
subscription_status_unpaid = 'unpaid'
subscription_status_cancelled = 'cancelled'
subscription_status = (
    (subscription_status_trial, gettext_lazy('Trial')),
    (subscription_status_active, gettext_lazy('Active')),
    (subscription_status_pastdue, gettext_lazy('Past Due')),
    (subscription_status_unpaid, gettext_lazy('Unpaid')),
    (subscription_status_cancelled, gettext_lazy('Cancelled')),
)

transaction_ttype_fee = 'fee'
transaction_ttype_charge = 'charge'
transaction_ttype_payout = 'payout'
transaction_ttype_transfer = 'transfer'
transaction_ttype = (
    (transaction_ttype_charge, gettext_lazy('Charge')),
    # TODO: Activate when models are created
    # (transaction_ttype_fee, gettext_lazy('Fee')),
    # (transaction_ttype_payout, gettext_lazy('Payout')),
    # (transaction_ttype_transfer, gettext_lazy('Transfer')),
)
transaction_otype_in = 'in'
transaction_otype_out = 'out'
transaction_otype = (
    (transaction_otype_in, gettext_lazy('In')),
    (transaction_otype_out, gettext_lazy('Out')),
)
transaction_method_card = 'card'
transaction_method_bank = 'bank'
transaction_method_customer = 'customer'
transaction_method_store = 'store'
transaction_method_bankaccount = 'bank_account'
transaction_method = (
    (transaction_method_card, gettext_lazy('Card')),
    # TODO: Activate when models are created
    # (transaction_method_store, gettext_lazy('Store')),
    # (transaction_method_bank, gettext_lazy('Bank Account')),
)
transaction_status_completed = 'completed'
transaction_status_inprogress = 'in_progress'
transaction_status_failed = 'failed'
transaction_status = (
    (transaction_status_completed, gettext_lazy('Completed')),
    (transaction_status_inprogress, gettext_lazy('In Progress')),
    (transaction_status_failed, gettext_lazy('Failed')),
)
transaction_currency_mxn = 'MXN'
transaction_currency_usd = 'USD'
transaction_currency = (
    (transaction_currency_mxn, gettext_lazy('MXN')),
    (transaction_currency_usd, gettext_lazy('USD')),
)
